IdentityApp/Controllers/DashboardsController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
//using AspnetCoreMvcFull.Models;

namespace AspnetCoreMvcFull.Controllers;

public class DashboardsController : Controller
{
  public IActionResult Index() => View();
}

IdentityApp/Views/Shared/Sections/Navbar/_Navbar.cshtml
@{
  TempData.Keep();
  @* ViewData["navbarDetached"] = (ViewData["navbarDetached"] ?? "navbar-detached"); *@
  ViewData["navbarDetached"] = (ViewData["navbarDetached"] ??= null);
  ViewData["containerNav"] = (ViewData["containerNav"] ??= "container-fluid");
}
@if (@ViewData["navbarDetached"] != null)
{
  <nav
  class='layout-navbar @((@ViewData["navbarDetached"] != null) ? @ViewData["navbarDetached"] : "") @((@ViewData["navbarDetached"] != null) ? @ViewData["containerNav"] : "") navbar navbar-expand-xl align-items-center bg-navbar-theme'
  id="layout-navbar">
  @await Html.PartialAsync("Sections/Navbar/_NavbarPartial")
  </nav>
}
else
{
  <nav
  class='layout-navbar @((@ViewData["navbarDetached"] != null) ? @ViewData["navbarDetached"] : "") @((@ViewData["navbarDetached"] != null) ? @ViewData["containerNav"] : "") navbar navbar-expand-xl align-items-center bg-navbar-theme'
  id="layout-navbar">
  <div class='@((@ViewData["navbarDetached"] == null) ? @ViewData["containerNav"] : "")'>
    @await Html.PartialAsync("Sections/Navbar/_NavbarPartial")
    </div>
  </nav>

}

IdentityApp/Views/Shared/Sections/Navbar/_NavbarPartial.cshtml
@* ! Brand demo (display only for navbar-full and hide on below xl) *@
@if (ViewData["navbarFull"] != null)
{
<div class="navbar-brand app-brand demo d-none d-xl-flex py-0 me-4">
  <a asp-controller="Dashboards" asp-action="Index" class="app-brand-link gap-2">
      <span class="app-brand-logo demo">
        @await Html.PartialAsync("../_Partials/_Macros")
      </span>
      <span class="app-brand-text demo menu-text fw-bold">@TempData.Peek("appName")</span>
    </a>
</div>
}

@* ! Not required for layout-without-menu *@
@if (ViewData["navbarHideToggle"] == null)
{
  <div class="layout-menu-toggle navbar-nav align-items-xl-center me-4 me-xl-0 d-xl-none">
    <a class="nav-item nav-link px-0 me-xl-6" href="javascript:void(0)">
      <i class="bx bx-menu bx-md"></i>
    </a>
  </div>
}

<div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">

  <!-- Search -->
 @*  <div class="navbar-nav align-items-center">
    <div class="nav-item d-flex align-items-center">
        <i class="bx bx-search bx-md"></i>
      <input type="text" class="form-control border-0 shadow-none ps-1 ps-sm-2" placeholder="Search..." aria-label="Search...">
    </div>
  </div> *@
  <!-- /Search -->

  <ul class="navbar-nav flex-row align-items-center ms-auto">
    <!-- Place this tag where you want the button to render. -->
    <li class="nav-item lh-1 me-4">
      <a class="github-button" href="https://github.com/themeselection/sneat-bootstrap-html-aspnet-core-mvc-admin-template-free" data-icon="octicon-star" data-size="large" data-show-count="true" aria-label="Star themeselection/sneat-html-admin-template-free on GitHub">Star</a>
    </li>

    <!-- User -->
    <li class="nav-item navbar-dropdown dropdown-user dropdown">
      <a class="nav-link dropdown-toggle hide-arrow p-0" href="javascript:void(0);" data-bs-toggle="dropdown">
        <div class="avatar avatar-online">
          <img src="~/img/avatars/1.png" alt class="w-px-40 h-auto rounded-circle">
        </div>
      </a>
      <ul class="dropdown-menu dropdown-menu-end">
        <li>
          <a class="dropdown-item" href="javascript:void(0);">
            <div class="d-flex">
              <div class="flex-shrink-0 me-3">
                <div class="avatar avatar-online">
                  <img src="~/img/avatars/1.png" alt class="w-px-40 h-auto rounded-circle">
                </div>
              </div>
              <div class="flex-grow-1">
                <h6 class="mb-0">John Doe</h6>
                <small class="text-muted">Admin</small>
              </div>
            </div>
          </a>
        </li>
        <li>
          <div class="dropdown-divider my-1"></div>
        </li>
        <li>
          <a class="dropdown-item" href="javascript:void(0);">
            <i class="bx bx-user bx-md me-2"></i>
            <span>My Profile</span>
          </a>
        </li>
        <li>
          <a class="dropdown-item" href="javascript:void(0);">
            <i class="bx bx-cog bx-md me-2"></i>
            <span>Settings</span>
          </a>
        </li>
        <li>
          <a class="dropdown-item" href="javascript:void(0);">
            <span class="d-flex align-items-center align-middle">
              <i class="flex-shrink-0 bx bx-credit-card bx-md me-3"></i>
              <span class="flex-grow-1 align-middle">Billing Plan</span>
              <span class="flex-shrink-0 badge rounded-pill bg-danger">4</span>
            </span>
          </a>
        </li>
        <li>
          <div class="dropdown-divider my-1"></div>
        </li>
        <li>
          <a class="dropdown-item" href="javascript:void(0);">
            <i class="bx bx-power-off bx-md me-2"></i>
            <span>Log Out</span>
          </a>
        </li>
      </ul>
    </li>
    <!--/ User -->

  </ul>
</div>